-- Active: 1737572179011@@127.0.0.1@3306@projet
DROP TABLE IF EXISTS Location_jeux;
DROP TABLE IF EXISTS Paiments;
DROP TABLE IF EXISTS Factures;
DROP TABLE IF EXISTS Jeux;
DROP TABLE IF EXISTS Locations;
DROP TABLE IF EXISTS Utilisateurs;

CREATE DATABASE IF NOT EXISTS projet;
USE projet;

