-- Active: 1739460525589@@127.0.0.1@3306@projet
    DROP TABLE IF EXISTS Location_jeux;
    DROP TABLE IF EXISTS Paiments;
    DROP TABLE IF EXISTS Factures;
    DROP TABLE IF EXISTS Jeux;
    DROP TABLE IF EXISTS Locations;
    DROP TABLE IF EXISTS Utilisateurs;

    DROP DATABASE IF EXISTS projet;
    CREATE DATABASE projet;
